/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2022-07-24 09:35:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class hotellist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/6764beb43d.js\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"row g-0\">\r\n");
      out.write("\t\t\t<!-- Wrapper -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<nav class=\"col-2  bg-light pe-3 border-right position-sticky\">\r\n");
      out.write("\t\t\t\t<!-- Left Side Nav -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<h1 class=\"h4 py-3 text-center text-primary\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fa-solid fa-earth-oceania\"></i> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"d-none d-lg-inline\">Travel Advisor</span>\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"list-group text-center text-lg-start\">\r\n");
      out.write("\t\t\t\t\t<span class=\"list-group-item disabled d-none d-lg-block\"> \r\n");
      out.write("\t\t\t\t\t<small>CONTROLS</small>\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t <a href=\"dashboard.jsp\" class=\"list-group-item list-group-item-action \">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-home\"></i> \r\n");
      out.write("\t\t\t\t\t\t<span class=\"d-none d-lg-inline\">Dashboard</span>\r\n");
      out.write("\t\t\t\t\t</a> \r\n");
      out.write("\t\t\t\t\t<a href=\"/Project_Testing/placelist.jsp\" class=\"list-group-item list-group-item-action\"> \r\n");
      out.write("\t\t\t\t\t<i class=\"fa-solid fa-location-dot\"></i> \r\n");
      out.write("\t\t\t\t\t\t<span class=\"d-none d-lg-inline\">Places</span> </a>\r\n");
      out.write("\t\t\t\t\t\t <a href=\"/Project_Testing/hotellist.jsp\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"list-group-item list-group-item-action active\"> \r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa-solid fa-hotel\"></i>\r\n");
      out.write("\t\t\t\t\t\t <span class=\"d-none d-lg-inline\">Hotels</span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t <a href=\"#\" class=\"list-group-item list-group-item-action\">\r\n");
      out.write("\t\t\t\t\t  <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fa-solid fa-face-smile\"></i> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"d-none d-lg-inline\">Attraction</span> </a>\r\n");
      out.write("\t\t\t\t\t\t <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"list-group-item list-group-item-action\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fa-solid fa-utensils\"></i> <span class=\"d-none d-lg-inline\">Restaurant</span>\r\n");
      out.write("\t\t\t\t\t</a> \r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"list-group-item list-group-item-action\">\r\n");
      out.write("\t\t\t\t\t <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fa-solid fa-circle-question\"></i> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"d-none d-lg-inline\">Forum</span> </a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"list-group-item list-group-item-action\">\r\n");
      out.write("\t\t\t\t\t\t <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fa-solid fa-key\"></i> <span class=\"d-none d-lg-inline\">Change\r\n");
      out.write("\t\t\t\t\t\t\tPassword</span> </a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t<!-- Left Side Nav -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<main class=\"col-10 bg-secondary\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("\t\t\t\t<div class=\"flex-fill\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"navbar nav\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a href=\"#\" class=\"nav-link\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa-solid fa-right-from-bracket\"></i> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"d-none d-lg-inline\">Log out</span> </a></li>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"container-fluid mt-3 p-4\">\r\n");
      out.write("\t\t\t\t<!-- Content -->\r\n");
      out.write("\r\n");
      out.write("                  <h2 class=\"h4 text-light m-2\">Hotel List</h2>\r\n");
      out.write("\t\t<div class=\"card mb-3\">\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t<div class=\"text-start\">\r\n");
      out.write("\t\t\t<div class=\"dropdown\">\r\n");
      out.write("\t\t\t<button class=\"btn btn-outline-secondary dropdown-toggle\" data-bs-toggle=\"dropdown\">Ngwe Saung</button>\r\n");
      out.write("\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t<li><a href=\"#\" class=\"dropdown-item\">Bagan</a>\r\n");
      out.write("\t\t\t<li><a href=\"#\" class=\"dropdown-item\">Inle Lake</a>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"text-end\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-sm btn-outline-secondary\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa-solid fa-plus\"></i>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>No.</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Name</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Phone No</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Description</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<th>Price Range</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Type</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Update</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Delete</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>1</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"d-flex align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"src/Hotel/eskala.jpg\" alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 45px; height: 45px\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ms-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"fw-bold mb-1\">ESKALA HOTELS & RESORTS</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>+954240341</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td>Eskala Hotals & Resorts Ngwe Saung is the premier\r\n");
      out.write("\t\t\t\t\t\t\tbeachfront destination in Myanmar, offering stylish rooms and\r\n");
      out.write("\t\t\t\t\t\t\tvillas with charming ocean views.</td>\r\n");
      out.write("\t\t\t\t\t\t<td>100000-300000 MMK</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Luxury</td>\r\n");
      out.write("\t\t\t\t\t\t<td><button class=\"btn btn-sm btn-outline-secondary\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa-solid fa-pen-to-square\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</button></td>\r\n");
      out.write("\t\t\t\t\t\t<td><button class=\"btn btn-sm btn-outline-secondary\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa-solid fa-trash-can\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</button></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>2</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"d-flex align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"src/Hotel/ria.jpg\" alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 45px; height: 45px\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ms-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"fw-bold mb-1\">RIA HOTEL & RESORT</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>+959422777007</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td>RIA Hotel-Resort is situated on Ngwe Saung's Beach front\r\n");
      out.write("\t\t\t\t\t\t\tarea, next to the Kyauk Gyi Stream. RIA Resort boasts\r\n");
      out.write("\t\t\t\t\t\t\taccommodations with an on-site Restaurant and Stunning Sea Views.</td>\r\n");
      out.write("\t\t\t\t\t\t<td>50000-200000 MMK</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Friendly</td>\r\n");
      out.write("\t\t\t\t\t\t<td><button class=\"btn btn-sm btn-outline-secondary\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa-solid fa-pen-to-square\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</button></td>\r\n");
      out.write("\t\t\t\t\t\t<td><button class=\"btn btn-sm btn-outline-secondary\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa-solid fa-trash-can\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</button></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>3</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"d-flex align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"src/Hotel/ace.jpg\" alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 45px; height: 45px\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ms-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"fw-bold mb-1\">ACE HOTEL</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>+959260111939</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td>HOTEL ACE Ngwe Saung provides comfortable 3-star\r\n");
      out.write("\t\t\t\t\t\t\taccommodation.The hotel features both a restaurant and a bar\r\n");
      out.write("\t\t\t\t\t\t\twhere guests can unwind at the end of the day.</td>\r\n");
      out.write("\t\t\t\t\t\t<td>50000-100000 MMK</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Budget</td>\r\n");
      out.write("\t\t\t\t\t\t<td><button class=\"btn btn-sm btn-outline-secondary\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa-solid fa-pen-to-square\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</button></td>\r\n");
      out.write("\t\t\t\t\t\t<td><button class=\"btn btn-sm btn-outline-secondary\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa-solid fa-trash-can\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</button></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- Content Row 1 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Content --> </main>\r\n");
      out.write("\t\t\t<!-- Main (Nav & Content) -->\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- Wrapper -->\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div> <!-- Container -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
